[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
fuzz.runs = 256
invariant.runs = 128
invariant.depth = 32
fs_permissions = [{ access = "read-write", path = "../shared/deployments" }]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
