import { FlatCompat } from "@eslint/eslintrc";
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });
const config = [
  // next-env.d.ts is generated by Next.js and contains a triple-slash route
  // reference that the TypeScript ESLint rule correctly rejects in authored
  // code. Keep generated files out of the application lint surface.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];
export default config;
